#!/bin/bash

echo "*Make sure you run the following command if you are not in env mode*"
echo "*********************source env/bin/activate************************"
echo -e "\n********************************************************************"
read -p "What is your project ID? " projectID
read -p "What is your model ID? " modelID


googlesamples-assistant-hotword --project-id $projectID --device-model-id $modelID 
