#!/bin/bash

echo -e "\n\n******************************************************************************"
echo "*Play a test sound (this will be a person speaking)                          *"
echo "*Press Ctrl+C when done                                                      *"
echo "*If you don't hear anything when you run this, check your speaker connection.*"
echo "******************************************************************************"
speaker-test -t wavd

