#!/bin/bash

#Step3
echo -e "\n******************************"
echo "*STEP3 [Generate Credentials]*"
echo -e "******************************\n"

#Install or update the authorization tool:
python -m pip install --upgrade google-auth-oauthlib[tool]

#Generate credentials to be able to run the sample code and tools. Reference the JSON file you downloaded in a previous step; you may need to copy it the device. Do not rename this file.
google-oauthlib-tool --scope https://www.googleapis.com/auth/assistant-sdk-prototype \
      --scope https://www.googleapis.com/auth/gcm \
      --save --headless --client-secrets client*
