#!/bin/bash

#Step1

echo -e "\n****************************"
echo "*STEP1 [Setting up the env]*"
echo "****************************"

echo -e "\n\nPlease make sure you move your client credential JSON file to current directory [`echo $PATH`]\n\n"
sleep 5

sudo apt-get update
echo -e  "\n*Choose a python version available on your system.*"
echo "*The one you are going to use for this project.****"
echo " 1)Python3 [Recommended]"
echo -e  " 2)Python2.7\n\n"
read -p "Enter either '1' or '2':   " version

case $version in
1)
	echo -e "\n*****************"
	echo "*Python3 Chosen!*"
	echo -e "*****************\n"
	sleep 3
	sudo apt-get install python3-dev python3-venv
	python3 -m venv env
	env/bin/python -m pip install --upgrade pip setuptools wheel
	sudo apt-get autoremove -y
	;;
2)
	echo "*******************"
	echo "*Python2.7 Chosen!*"
	echo "*******************"
	sudo apt-get update
	sudo apt-get install python-dev python-virtualenv
	virtualenv env --no-site-packages
	env/bin/python -m pip install --upgrade pip setuptools wheel
	;;
*)
	echo "Input Error,please re-run the script"
esac

echo ""
echo "PLease Type the following into your terminal"
echo "*************************"
echo "*source env/bin/activate*"
echo "*************************"
